<div class="alert alert-block alert-success">
    <h1 align="center">Zeynab Khorshidi</h1>
</div>

In [29]:
import numpy as np
import pandas as pd
import cv2

In [30]:
image = cv2.imread('1.jpg',0)

In [31]:
cv2.imshow('first',image)

In [32]:
print(image)

[[209 225 218 ... 135 159 170]
 [180 209 242 ... 129 163 161]
 [188 209 228 ... 119 161 162]
 ...
 [ 75  85  82 ...  83  85  84]
 [ 78  85  77 ...  85  87  86]
 [ 74  82  72 ...  86  89  89]]


In [33]:
image

array([[209, 225, 218, ..., 135, 159, 170],
       [180, 209, 242, ..., 129, 163, 161],
       [188, 209, 228, ..., 119, 161, 162],
       ...,
       [ 75,  85,  82, ...,  83,  85,  84],
       [ 78,  85,  77, ...,  85,  87,  86],
       [ 74,  82,  72, ...,  86,  89,  89]], dtype=uint8)

In [34]:
print('Height of image:',(image.shape[0],'pixels'))
print('Width of image:',(image.shape[1],'pixels'))

Height of image: (100, 'pixels')
Width of image: (100, 'pixels')


In [35]:
first_mask=np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

In [36]:
print(first_mask)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [37]:
image_padding_3 = np.pad(image, (1, 1))       
print(image_padding_3)

[[  0   0   0 ...   0   0   0]
 [  0 209 225 ... 159 170   0]
 [  0 180 209 ... 163 161   0]
 ...
 [  0  78  85 ...  87  86   0]
 [  0  74  82 ...  89  89   0]
 [  0   0   0 ...   0   0   0]]


In [38]:
print('Height of image:',(image_padding_3.shape[0],'pixels'))
print('Width of image:',(image_padding_3.shape[1],'pixels'))

Height of image: (102, 'pixels')
Width of image: (102, 'pixels')


In [39]:
sum_first_mask = np.sum(first_mask)
print(sum_first_mask)

9


In [40]:
zarib_3 = 1/sum_first_mask
print(zarib_3)

0.1111111111111111


In [41]:
for i in range(100):
    for j in range(100):
        image_padding_3[i+1][j+1] = ((image_padding_3[i][j] * zarib_3) 
                                  + (image_padding_3[i][j+1] * zarib_3)
                                  + (image_padding_3[i][j+2] * zarib_3)
                                  + (image_padding_3[i+1][j] * zarib_3)
                                  + (image_padding_3[i+1][j+1] * zarib_3)
                                  + (image_padding_3[i+1][j+2] * zarib_3)
                                  + (image_padding_3[i+2][j] * zarib_3)
                                  + (image_padding_3[i+2][j+1] * zarib_3)
                                  + (image_padding_3[i+2][j+2] * zarib_3))

In [42]:
print(image_padding_3)

[[  0   0   0 ...   0   0   0]
 [  0  91 129 ...  96  65   0]
 [  0 111 170 ... 125  85   0]
 ...
 [  0  48  70 ...  81  52   0]
 [  0  30  42 ...  49  30   0]
 [  0   0   0 ...   0   0   0]]


In [43]:
image_padding_3 = image_padding_3[1:-1,1:-1]

In [44]:
print(image_padding_3)

[[ 91 129 128 ...  84  96  65]
 [111 170 179 ... 117 125  85]
 [121 183 200 ... 130 136  93]
 ...
 [ 48  71  76 ...  84  80  51]
 [ 48  70  76 ...  85  81  52]
 [ 30  42  46 ...  53  49  30]]


In [45]:
cv2.imshow("End3",image_padding_3)

In [46]:
second_mask=np.array([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1]
])

In [47]:
print(second_mask)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [48]:
image_padding_5 = np.pad(image, (2, 2))       
print(image_padding_5)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 209 ... 170   0   0]
 ...
 [  0   0  74 ...  89   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [49]:
print('Height of image:',(image_padding_5.shape[0],'pixels'))
print('Width of image:',(image_padding_5.shape[1],'pixels'))

Height of image: (104, 'pixels')
Width of image: (104, 'pixels')


In [50]:
sum_second_mask = np.sum(second_mask)
print(sum_second_mask)

25


In [51]:
zarib_5 = 1/sum_second_mask
print(zarib_5)

0.04


In [52]:
for i in range(100):
    for j in range(100):
        image_padding_5[i+2][j+2] = ((image_padding_5[i][j] * zarib_5) 
        + (image_padding_5[i][j+1] * zarib_5)
        + (image_padding_5[i][j+2] * zarib_5)
        + (image_padding_5[i][j+3] * zarib_5)
        + (image_padding_5[i][j+4] * zarib_5)
        + (image_padding_5[i+1][j] * zarib_5)
        + (image_padding_5[i+1][j+1] * zarib_5)
        + (image_padding_5[i+1][j+2] * zarib_5)
        + (image_padding_5[i+1][j+3] * zarib_5)
        + (image_padding_5[i+1][j+4] * zarib_5) 
        + (image_padding_5[i+2][j] * zarib_5)
        + (image_padding_5[i+2][j+1] * zarib_5)
        + (image_padding_5[i+2][j+2] * zarib_5)
        + (image_padding_5[i+2][j+3] * zarib_5)
        + (image_padding_5[i+2][j+4] * zarib_5)
        + (image_padding_5[i+3][j] * zarib_5)
        + (image_padding_5[i+3][j+1] * zarib_5)
        + (image_padding_5[i+3][j+2] * zarib_5)
        + (image_padding_5[i+3][j+3] * zarib_5) 
        + (image_padding_5[i+3][j+4] * zarib_5)
        + (image_padding_5[i+4][j] * zarib_5)
        + (image_padding_5[i+4][j+1] * zarib_5)
        + (image_padding_5[i+4][j+2] * zarib_5)
        + (image_padding_5[i+4][j+3] * zarib_5)
        + (image_padding_5[i+4][j+4] * zarib_5))

In [53]:
print(image_padding_5)

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 76 ... 48  0  0]
 ...
 [ 0  0 20 ... 19  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [54]:
image_padding_5 = image_padding_5[2:-2,2:-2]

In [55]:
print(image_padding_5)

[[ 76  94 106 ...  82  63  48]
 [ 86 111 131 ... 100  77  57]
 [100 131 159 ... 129 100  73]
 ...
 [ 41  54  69 ...  79  62  44]
 [ 31  42  53 ...  61  47  33]
 [ 20  26  33 ...  39  29  19]]


In [56]:
cv2.imshow("End5",image_padding_5)